### ISSUE TITLE
unigame already exists !

### ISSUE THREAD

**Issue by jice-nospam** [edwin0cheng/unrust#10]
https://github.com/unigame

Should we change the name ?

**Comment by edwin0cheng** [comment]
Ohno, we should change the name then, btw the current one is just a temp name . 

Do you have any suggestions ? My only requirement is started with "un" :)

**Comment by jice-nospam** [comment]
unity, unreal and unigine are nice :) 

These are a few proposals based on english word, but we can also make up a name

Some showing that the engine is not limiting you :
* uncaged
* unchain/unchained
* unlock/unlocked

undercover
undergod
undertaker
underworld
unicorn
union
unique
unrest
unstoppable

**Comment by edwin0cheng** [comment]
unigine are nice , but already exits too.
And other names are already exits to (uncaged and unchain),
Um... would you think it is very weird if we named it "unrust" ? haha

**Comment by jice-nospam** [comment]
:) unrust is fine

**Comment by edwin0cheng** [comment]
Then i would change it later ^^ and then i would close this.

**Comment by edwin0cheng** [comment]
The whole project name changed.
