### ISSUE TITLE
Illegal instruction when running native on macOS

### ISSUE THREAD

**Issue by johnthagen** [edwin0cheng/unrust#45]
On macOS when I run:

```
$ rustup override set nightly
$ cargo run --example boxes --release
    Finished release [optimized] target(s) in 0.24 secs
     Running `target/release/examples/boxes`
Illegal instruction: 4
```

My `rustup` toolchain, which I updated April 16, 2018.

```
$ rustup show
active toolchain
----------------

nightly-x86_64-apple-darwin (directory override for '/Users/user/GitHub/unrust')
rustc 1.27.0-nightly (7360d6dd6 2018-04-15)
```

Is this a known issue? I'm running macOS 10.12.6.

Edit: Perhaps related to the pinned `nightly-2018-04-01` in Travis config?

**Comment by edwin0cheng** [comment]
Yes i just confirm that in my machine. And it seem to be a **NEW** bug from recent rustc nightly.
For the work around right now, you can pinned to the `nightly-2018-04-01`.
I'm investigating more and will fill new issue to rustc side

Thanks for the report.

**Comment by edwin0cheng** [comment]
Reported: https://github.com/rust-lang/rust/issues/50018

**Comment by edwin0cheng** [comment]
Okay, i finally found that it maybe related to winit crate, i just bump the version of glutin to 0.14, and it should works now, Could you mind to test it again ?

**Comment by johnthagen** [comment]
Works now, thanks!
